# files/etc/opkg/customfeeds.conf
# 与 openwrt-24.10 分支对应的稳定包源

src/gz openwrt_core https://downloads.openwrt.org/releases/24.10-SNAPSHOT/targets/qualcommax/ipq60xx/packages
src/gz openwrt_base https://downloads.openwrt.org/releases/24.10-SNAPSHOT/packages/aarch64_cortex-a53/base
src/gz openwrt_luci https://downloads.openwrt.org/releases/24.10-SNAPSHOT/packages/aarch64_cortex-a53/luci
src/gz openwrt_packages https://downloads.openwrt.org/releases/24.10-SNAPSHOT/packages/aarch64_cortex-a53/packages
src/gz openwrt_routing https://downloads.openwrt.org/releases/24.10-SNAPSHOT/packages/aarch64_cortex-a53/routing
src/gz openwrt_telephony https://downloads.openwrt.org/releases/24.10-SNAPSHOT/packages/aarch64_cortex-a53/telephony

src/gz tuna_core https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/24.10-SNAPSHOT/targets/qualcommax/ipq60xx/packages
src/gz tuna_base https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/24.10-SNAPSHOT/packages/aarch64_cortex-a53/base
src/gz tuna_luci https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/24.10-SNAPSHOT/packages/aarch64_cortex-a53/luci
src/gz tuna_packages https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/24.10-SNAPSHOT/packages/aarch64_cortex-a53/packages
src/gz tuna_routing https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/24.10-SNAPSHOT/packages/aarch64_cortex-a53/routing

src/gz kiddin9 https://op.supes.top/packages/aarch64_cortex-a53
